### ISSUE TITLE
Documentation site refactoring

### ISSUE THREAD

**Issue by d4g0** [antfu/vueuse#242] opened 2020-12-07 01:22 UTC
I find vueuse super helpful, it will be nice to have the docs page alive for those offline moments when we need a reference.

**Comment by antfu** [comment] 2020-12-07 06:38
Thanks for bringing this up. As I would love to have PWA support for VueUse since a long time ago, however, I am not sure if Storybook support PWA at all. I am planning to refactor the documentation site into vite or vitepress. It requires quite some non-trivial refactoring but I don't have much bandwidth on this at this moment. If somebody gets interested in this, feel free to make a draft PR and then we can have some discussion.

Thanks.

**Comment by seifsay3d** [comment] 2020-12-22 14:40
Hello @antfu, I'm interested in picking this up. Is something like https://pikax.me/vue-composable/#introduction what you are looking for but with vitepress instead of vuepress?

**Comment by antfu** [comment] 2020-12-22 14:54
Yes, the main problem here is that I want to keep the current file structure (code, test, docs within the same folder) while having a bit of customization. I am not sure if Vitepress can have such levels of flexibility. I might end up using Vite with some plugins, probably from [Vitesse](https://github.com/antfu/vitesse) which has MD support and SSG built-in.

It would be great if you are interested in helping out! Thank you!

/cc @matias-capeletto I saw you are using a customized Vitepress for you blog and you are actively contributing to Vitepress (and good job!👍). Can I have some of your insight into whether we can have Vitepress setup for our documantion? Thanks.

**Comment by matias-capeletto** [comment] 2020-12-22 16:00
I was thinking about this issue too, it would be great to move, especially for mobile users. Great that you are interested @seifsay3d!

I think it would be great if we could use Vitepress. The main issue at this point is that it is not mature enough, so we may bump into issues from time to time. But if we manage to get a setup working, we can avoid updating too often and we should be fine with that. Vue Router is going to use it: https://github.com/vuejs/vue-router-next and this is how it looks: https://next.router.vuejs.org/
For my blog, I initially copied their setup, and we could do the same (there are some issues in the latest release for example, and they reverted to a prev one)

There isn't a dark theme yet. It is easy to grab the default theme, and clone it in the `.vitepress/theme` folder and modify it as we wish. I ended up doing that. In the future I think all colors will be using css variables, so we could just modify that. Somebody surely will create a theme with dark/light support also. 

In order to maintain the current structure, I was thinking that the path to the .md file for each composable would be added automatically (like you do in update.ts) to the .vitepress/config.js sidebar. 

One issue there is that as far as I understand the links are currently generated using the folders path, so they would look like vueuse.js.org/packages/core/asyncComputed/index.html
It doesn't look bad though. If something else is desired, maybe this is a good feature to add to vitepress later

We should be able to add the stories for each composable in the .md. I was thinking that this will be manual like:

```
# someComposable

<script setup>
import Showcase from './index.stories.tsx'
</script>
<Showcase>

... the docs ...
```

Another way is to add this to the theme, and use frontmatter to define where the story is, something like:

```
---
story: './index.stories.tsx'
---
# someComposable

... the docs ...
```

So the only manual thing would be adding a `story` entry in frontmatter (behind the scene, it would import that story and add it to the docs.
I think this should be possible, but I didn't test it. If this works, I think the manual boilerplate is ok.

To me, long term, it would be great that VueUse would use Vitepress, as there is some work cooking there that would be great to take advantage of. Short term, I am not sure, it is really tempting to at least try to get a setup working with it.
The DX experience of Vitepress is just too good 😃 
But with Vite as you said @antfu, we would also have that experience when authoring the docs so that should be goog too.

**Comment by antfu** [comment] 2020-12-22 16:20
Thanks for the detailed info @matias-capeletto! I was trying to migrate my site from Gridsome to Vitepress and writing the custom theme a couple of days ago. I end up switching to Vite directly cause I have found out that Vitepress does not allow for customizing `vite.config.ts`.

But as VueUse's docs do not need that many customizations as my site and after your explanations, I think it's better to use Vitepress as it handles HMR and payloads much better. I'd love to give it a try!

> The main issue at this point is that it is not mature enough

Not a problem for me, I am happy to migrate and keep it up to date.

> Links are currently generated using the folders path

Yeah, that's my main concern. I have a silly idea of mirroring(copying) the files to some folder like `/docs` with proper structure. Or maybe we can somehow hijack the fs module to serve the files in the virtual location (not sure if it's doable, but I am really fanatical about hacks I suppose 😅).

> it would be great that VueUse would use Vitepress

TRUE. I actually have no idea why I have chosen Storybook at the beginning (it's so bad to me in many means). This is long pain to me and I am really happy to see this get refactored.

Thanks ahead for everybody involved :P

**Comment by matias-capeletto** [comment] 2020-12-22 16:38
>  I have a silly idea of mirroring(copying) the files to some folder like /docs with proper structure. Or maybe we can somehow hijack the fs module to serve the files in the virtual location (not sure if it's doable, but I am really fanatical about hacks I suppose 😅).

I also thought about this 😄 
Because I wanted to also avoid having to add the frontmatter or Showcase snippet by hand to each md. That pieces can be assembled in `docs/core/`, `docs/shared`, etc. And then run vitepress. 
But I discarded the idea because I do not know how we will get the benefits of vite DX while authoring with this setup. Maybe there will be a watch process so when you save it updates things in docs/? If you manage to keep vite HMR working, that would be really cool

> I actually have no idea why I have chosen Storybook 

Well, they have a lot of good ideas. I love how far they pushed documentation for design systems. I hope there will exist a Vitebook in the future though, so people do not need to endure webpack bundling 😃 
But indeed I like a lot more for libs the docs a la vuepress/vitepress, the vue ecosystem is amazing in this regard.

I think the setup of separate dirs with docs, tests, and a story that VueUse has is really nice for utility libraries. Maybe at one point this could be a theme for vitepress in its own repo.

**Comment by antfu** [comment] 2020-12-22 20:56
OK, I made a quick setup on https://github.com/antfu/vueuse/tree/vitepress branch and it looks pretty promising! 🎉

Preview: https://vitepress--vueuse.netlify.app/


<sub>(a little hydration mismatching for the front page for some reasons, but not a big problem)</sub>

A quick TODO list here, feel free to take any of them and make PRs against the `vitepress` branch

- [ ] Rewrite `index.stories.tsx` to `Demo.vue` and `info.json` (better to write a script to automate)
- [ ] Rewrite the `scripts/docs-loader.js` to update the `index.md` files directly (magic comments might be helpful)
- [ ] Setup a custom theme with dark mode support
- [ ] Auto demo injecting

Thank you!

**Comment by matias-capeletto** [comment] 2020-12-22 21:22
Wow, that was fast. And it looks really good already 🎉  

There is an issue discussing why the frontpage is being duplicated everywhere in Vitepress: https://github.com/vuejs/vitepress/issues/177

Looks like there are two options, in that thread they said the issue is gone if you use Vue 3.0.3 (instead of Vue 3.0.4), or do what posva did, that reverted vitepress to 0.8.1 (https://github.com/vuejs/vue-router-next/blob/master/package.json#L104)
I do not know which one is better, maybe using Vue 3.0.3 is better if that fixes it so we can keep updating vitepress if there are changes we need

Nice renaming the demos to `Demo.vue`!

About `info.json`, that will hold the info for the category, for example?
What do you think if we use the frontmatter to define that information?

In index.md
```
---
vueuse:
  category: Utilities
  deprecated: true
head:
  ... meta description and other SEO props, twitter card, etc
---

... docs
```

In the theme and in the .md, we can accesses this info with the [global computed $frontmatter](https://vitepress.vuejs.org/guide/global-computed.html#page)

**Comment by antfu** [comment] 2020-12-22 22:11
That's a good point, let's use frontmatter!

But the hydration issue I am not in hurry looking for a solution, we are not ready anyway :P Thanks for the tips! (Since I started using Vitepress, I shall be more active make contributions to it 😉)

**Comment by seifsay3d** [comment] 2020-12-23 15:32
> OK, I made a quick setup on https://github.com/antfu/vueuse/tree/vitepress branch and it looks pretty promising! 🎉
> 
> Preview: https://vitepress--vueuse.netlify.app/
> 
> (a little hydration mismatching for the front page for some reasons, but not a big problem)
> 
> A quick TODO list here, feel free to take any of them and make PRs against the `vitepress` branch
> 
> * [ ]  Rewrite `index.stories.tsx` to `Demo.vue` and ~`info.json`~ fromtmatter in `index.md` (better to write a script to automate)
> * [ ]  Rewrite the `scripts/docs-loader.js` to update the `index.md` files directly (magic comments might be helpful)
> * [ ]  Setup a custom theme with dark mode support
> * [ ]  Auto demo injecting
> 
> Thank you!


Wow you are impressively fast, I’ll take a shot at these over the holidays

**Comment by antfu** [comment] 2020-12-23 17:12
Update: I wrote a script to generate `demo.vue` from `index.stories.tsx` and committed them to the branch. The generated SFCs are not always perfect, some of them might need to do some manual clean up. 
Looking for some help on this, if you have Vetur and ESLint installed on your VSCode, they should show you the errors when you open a damaged Vue SFC. Thanks.

**Comment by antfu** [comment] 2021-01-04 21:33
https://vitepress--vueuse.netlify.app/

We are pretty close now! There are some bugs that need to be fixed in vitepress. I will get them on track a bit later.

**Comment by matias-capeletto** [comment] 2021-01-04 21:46
This is awesome @antfu! It is really smooth on mobile now 🎉 

I can send a PR to get better scrollbars in win32 later. There is also a scrollbar that appears when using line highlights that is a bug in the default vitepress theme and I had fixed it in my blog. I will check that too.

**Closed** 2021-01-10 11:01 UTC
Labels: documentation, help wanted
