### ISSUE TITLE
Including @vueuse causes the vue instance to initialize twice @4.0.0-beta.4

### ISSUE THREAD

**Issue by Neophen** [antfu/vueuse#109] opened 2020-08-17 11:46 UTC
This took me a while to track down, but after upgrading to `@4.0.0-beta.4` my whole app started throwing a million errors as the main instance got initialised twice.

I used `@4.0.0-beta.2` fine.

Not even sure how to describe this bug.

The library has great potential! Thank you for your work. I only use one function from it so i will be removing it for now.

I wish i could provide a simple bug, but at the moment we're in crunch mode to launch production and this has cost me 2 days already :(

I might return back with a proper issue once i have time.

**Comment by antfu** [comment] 2020-08-17 12:34
Which one are you using?

**Comment by Neophen** [comment] 2020-08-18 14:40
beta.2 was working fine, beta.4 broke it and for some reason i can't get it to work even after downgrading it :(

**Comment by antfu** [comment] 2020-08-18 14:47
@Neophen Can you show me the error logs so I can better help with this? and which utilities are you imported from vueuse? Thanks

**Comment by lizy0329** [comment] 2020-10-30 04:31
"@vue/composition-api" should put in to `peerDependencies` not `dependencies` in package.json. Otherwise, It will throw an error by initializing twice if your project  in use composition-api. @antfu

**Comment by antfu** [comment] 2020-10-30 04:33
Can you try with the latest version? I don't think we have vca in our dependencies.

**Comment by lizy0329** [comment] 2020-10-30 05:29
> Can you try with the latest version? I don't think we have vca in our dependencies.

I can see [Vue.use(VueCompositionAPI)](https://github.com/antfu/vue-demi/blob/master/lib/v2/index.esm.js) in vue-demi. Due to vueuse vca is put in `dependencies `, if `vueuse-vca` version is different form `project-vca` it will download in `node_module/vueuse/node_module/@vue/composition-api`

**Comment by antfu** [comment] 2020-10-30 06:31
Neither VueUse nor Vue Demi have `@vue/composition-api` in `dependencies`. And Vue Demi does have a mechanism to prevent duplicated installation.

https://github.com/antfu/vueuse/blob/38e304c48b708c6e4ff2c1ce19de9ec6f4fd5c02/packages/core/package.json#L29
https://github.com/antfu/vue-demi/blob/d43e2e6906677c1629fc2db79ecbd1854931ea9a/package.json#L17

Please be sure to use the latest version of VueUse and Vue Demi. If you have multiple packages installed, you should consider rebuilding your lock file to keep them up-to-date.

Close this for now as the original issue does not seem to be active. If the problem still occurs to you, please open another issue with a minimal reproduction.

**Closed by antfu** 2020-10-30 06:32 UTC
Labels: needs reproduction

**Comment by lizy0329** [comment] 2020-10-30 06:49
OK, Thanks a lot
